apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: inventory-k8s
spec:
  selector:
    matchLabels:
      app: inventory-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: inventory-k8s
    spec:
      containers:
        - name: inventory-k8s
          image: vamshivoore/inventory-api:v1 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster